"""empty message

Revision ID: 3d47ff6aac16
Revises: 9a722e88bd70
Create Date: 2019-08-02 20:45:38.983184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d47ff6aac16'
down_revision = '9a722e88bd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('status', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'status')
    # ### end Alembic commands ###
