"""empty message

Revision ID: 3d5895b0b5e7
Revises: 4f13c0b30718
Create Date: 2019-08-03 19:12:24.652436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5895b0b5e7'
down_revision = '4f13c0b30718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ac_record', sa.Column('paper_id', sa.Integer(), nullable=True))
    op.add_column('ac_record', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ac_record', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'ac_record', 'paper', ['paper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ac_record', type_='foreignkey')
    op.drop_constraint(None, 'ac_record', type_='foreignkey')
    op.drop_column('ac_record', 'question_id')
    op.drop_column('ac_record', 'paper_id')
    # ### end Alembic commands ###
