"""empty message

Revision ID: 439f1b6fa835
Revises: 33e3845445a0
Create Date: 2019-08-04 22:54:16.591368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439f1b6fa835'
down_revision = '33e3845445a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ac_record_ibfk_3', 'ac_record', type_='foreignkey')
    op.drop_constraint('ac_record_ibfk_2', 'ac_record', type_='foreignkey')
    op.drop_constraint('ac_record_ibfk_1', 'ac_record', type_='foreignkey')
    op.create_foreign_key(None, 'ac_record', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ac_record', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'ac_record', 'paper', ['paper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ac_record', type_='foreignkey')
    op.drop_constraint(None, 'ac_record', type_='foreignkey')
    op.drop_constraint(None, 'ac_record', type_='foreignkey')
    op.create_foreign_key('ac_record_ibfk_1', 'ac_record', 'paper', ['paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ac_record_ibfk_2', 'ac_record', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ac_record_ibfk_3', 'ac_record', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
