"""empty message

Revision ID: 4f13c0b30718
Revises: 3ab1ffe0b504
Create Date: 2019-08-03 16:08:33.121530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f13c0b30718'
down_revision = '3ab1ffe0b504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'question', ['PID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='unique')
    # ### end Alembic commands ###
