"""empty message

Revision ID: 97896ea48e37
Revises: 1202167b0c6c
Create Date: 2019-08-04 17:02:35.046257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97896ea48e37'
down_revision = '1202167b0c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ac_record', sa.Column('backinfo', sa.Text(), nullable=True))
    op.add_column('ac_record', sa.Column('status', sa.String(length=1), nullable=False))
    op.alter_column('ac_record', 'act',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ac_record', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ac_record', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ac_record', 'act',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('ac_record', 'status')
    op.drop_column('ac_record', 'backinfo')
    # ### end Alembic commands ###
