"""empty message

Revision ID: 98f8b0f164f5
Revises: e46f40dc9073
Create Date: 2019-08-04 11:26:57.296839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f8b0f164f5'
down_revision = 'e46f40dc9073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LuoGu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LuoGu')
    # ### end Alembic commands ###
