"""empty message

Revision ID: b344acf0b9fc
Revises: 3d47ff6aac16
Create Date: 2019-08-02 21:07:06.991518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b344acf0b9fc'
down_revision = '3d47ff6aac16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('create_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'create_time')
    # ### end Alembic commands ###
