"""empty message

Revision ID: e46f40dc9073
Revises: 3d5895b0b5e7
Create Date: 2019-08-03 19:16:03.665305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46f40dc9073'
down_revision = '3d5895b0b5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ac_record', sa.Column('act', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ac_record', 'act')
    # ### end Alembic commands ###
